feat: add shell completions
DeterminateSystems/fh pull request #26
Opened 2023-09-06 12:49 UTC by ryanccn

This PR adds completions to the CLI using [clap_complete](https://docs.rs/clap_complete/latest/clap_complete/) and also installs the completions in the Nix package.

2023-09-12 14:13 UTC, lucperkins requested changes

2023-09-12 14:13 UTC, lucperkins commented on src/cli/cmd/mod.rs
> +    Completions(completions::CompletionsSubcommand),
kubectl, docker, hugo, and a lot of others use `<tool> completion <shell>` as their format. I'd prefer to stick with that format and make this `fh completion` instead.

2023-09-12 15:30 UTC, lucperkins commented
LGTM but I'm going to wait on a +1 from @cole-h

2023-09-13 14:31 UTC, cole-h approved these changes
LGTM, seems to work fine (when manually sourcing it in fish, at least).

2023-09-13 14:33 UTC, merged